city = [
{ "CityID": 1, "CityName": "北京市", "ProID": 1, "CitySort": 1 },
{ "CityID": 2, "CityName": "天津市", "ProID": 2, "CitySort": 2 }, 
{ "CityID": 3, "CityName": "石家庄市", "ProID": 3, "CitySort": 3},
{ "CityID": 4, "CityName": "廊坊市", "ProID": 3, "CitySort": 4 },   
{ "CityID": 5, "CityName": "保定市", "ProID": 3, "CitySort": 5 }, 
{ "CityID": 6, "CityName": "唐山市", "ProID": 3, "CitySort": 6 },
{ "CityID": 7, "CityName": "张家口市", "ProID": 3, "CitySort": 7 }, 
{ "CityID": 8, "CityName": "承德市", "ProID": 3, "CitySort": 8 }, 
{ "CityID": 9, "CityName": "邯郸市", "ProID": 3, "CitySort": 9},
{ "CityID": 10, "CityName": "沧州市", "ProID": 3, "CitySort": 10 }, 
{ "CityID": 11, "CityName": "衡水市", "ProID": 3, "CitySort": 11 }, 
{ "CityID": 12, "CityName": "邢台市", "ProID": 3, "CitySort": 12 },
{ "CityID": 13, "CityName": "秦皇岛市", "ProID": 3, "CitySort": 13 },
{ "CityID": 14, "CityName": "太原市", "ProID": 4, "CitySort": 14 },
{ "CityID": 15, "CityName": "大同市", "ProID": 4, "CitySort": 15 },
{ "CityID": 16, "CityName": "朔州市", "ProID": 4, "CitySort": 16 },
{ "CityID": 17, "CityName": "阳泉市", "ProID": 4, "CitySort": 17 },
{ "CityID": 18, "CityName": "长治市", "ProID": 4, "CitySort": 18 },
{ "CityID": 19, "CityName": "晋城市", "ProID": 4, "CitySort": 19 },
{ "CityID": 20, "CityName": "忻州市", "ProID": 4, "CitySort": 20 },
{ "CityID": 21, "CityName": "晋中市", "ProID": 4, "CitySort": 21 },
{ "CityID": 22, "CityName": "临汾市", "ProID": 4, "CitySort": 22 },
{ "CityID": 23, "CityName": "运城市", "ProID": 4, "CitySort": 22 },
{ "CityID": 24, "CityName": "吕梁市", "ProID": 4, "CitySort": 24 },
];

// { "CityID": 3, "CityName": "上海市", "ProID": 9, "CitySort": 3 }, 
// { "CityID": 4, "CityName": "重庆市", "ProID": 27, "CitySort": 4 },
// { "CityID": 370, "CityName": "澳门特别行政区", "ProID": 33, "CitySort": 370 }, 
// { "CityID": 371, "CityName": "香港特别行政区", "ProID": 34, "CitySort": 371}